default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: surakshya
  password: 2026
  pool: 5

development:
  <<: *default
  database: library_app_development

test:
  <<: *default
  database: library_app_test

production:
  <<: *default
  database: library_app_production
  username: library_app
  password: <%= ENV['LIBRARY_APP_DATABASE_PASSWORD'] %>
